require("config.pre-setup")
require("config.lazy")
require("config.persist-colorscheme")
require("options")
require("mason-lspconfig").setup()
require("config.formatting")
require("config.debuggers")
